[program:django]
command=conda run -n dubhe_visual python main.py --port 9898
directory=/dubhe-visual-server/backend
autostart=true
autorestart=unexpected
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:parser]
command=conda run -n dubhe_visual python master.py
directory=/dubhe-visual-server/parser_service
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:monitor]
command=conda run -n dubhe_visual python monitor.py
directory=/dubhe-visual-server/service_utils
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0